# ============================================
# Smart Hospital System - Production Deployment (Modified for Jenkins)
# ============================================

services:
  nginx:
    image: ${GATEWAY_IMAGE}:${IMAGE_TAG}
    container_name: hospital-gateway
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - auth-service
      - core-service
      - iot-service
      - chat-service
      - medical-chatbot
    networks:
      - hospital-network
    restart: always

  frontend:
    image: ${FRONT_IMAGE}:${IMAGE_TAG}
    container_name: hospital-frontend
    expose:
      - "80"
    networks:
      - hospital-network
    restart: always

  auth-service:
    image: ${AUTH_IMAGE}:${IMAGE_TAG}
    container_name: hospital-auth-service
    expose:
      - "4001"
    environment:
      - PORT=4001
      - DATABASE_URL=mongodb://mongo:27017/hospital_db
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    depends_on:
      - mongo
    networks:
      - hospital-network
    restart: always

  core-service:
    image: ${CORE_IMAGE}:${IMAGE_TAG}
    container_name: hospital-core-service
    expose:
      - "4002"
    environment:
      - PORT=4002
      - DATABASE_URL=mongodb://mongo:27017/hospital_db
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - CHAT_SERVICE_URL=http://chat-service:4004
    depends_on:
      - mongo
      - chat-service
    networks:
      - hospital-network
    restart: always

  iot-service:
    image: ${IOT_IMAGE}:${IMAGE_TAG}
    container_name: hospital-iot-service
    expose:
      - "4003"
    environment:
      - PORT=4003
      - DATABASE_URL=mongodb://mongo:27017/hospital_db
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    depends_on:
      - mongo
    networks:
      - hospital-network
    restart: always

  chat-service:
    image: ${CHAT_IMAGE}:${IMAGE_TAG}
    container_name: hospital-chat-service
    expose:
      - "4004"
    environment:
      - PORT=4004
      - DATABASE_URL=mongodb://mongo:27017/hospital_db
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    depends_on:
      - mongo
    networks:
      - hospital-network
    restart: always

  medical-chatbot:
    image: ${BOT_IMAGE}:${IMAGE_TAG}
    container_name: hospital-medical-chatbot
    expose:
      - "9090"
    environment:
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GEMINI_API_KEYS=${GEMINI_API_KEYS}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - FORCE_REINDEX=false
    networks:
      - hospital-network
    restart: always

  mongo:
    image: mongo:7
    container_name: hospital-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - hospital-network
    restart: always

networks:
  hospital-network:
    driver: bridge

volumes:
  mongo_data:
    driver: local
